<a href="https://colab.research.google.com/github/kaveesha82/DS_Project/blob/component-1/arrival_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_excel('/content/drive/MyDrive/DSGP/monthlyarrivals.xlsx')

In [4]:
#Clean column names
df.columns = df.columns.str.strip()

#Remove commas inside numbers
df = df.replace(",", "", regex=True)


df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1452 entries, 0 to 1451
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Year         1452 non-null   int64
 1   Month        1452 non-null   object
 2   Nationality  1452 non-null   object
 3   Arrivals     1452 non-null   int64
 4   Avg_Stay     1056 non-null   float64
 5   Revenue_USD  1056 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 68.2+ KB

In [5]:
df.shape

(1452, 6)

In [6]:
df.columns

Index(['Year', 'Month', 'Nationality', 'Arrivals', 'Avg_Stay', 'Revenue_USD'], dtype='object')

In [7]:
df.dtypes

Year             int64
Month           object
Nationality     object
Arrivals         int64
Avg_Stay       float64
Revenue_USD    float64
dtype: object

In [8]:
df.isnull().sum()

Year             0
Month            0
Nationality      0
Arrivals         0
Avg_Stay       396
Revenue_USD    396
dtype: int64

In [9]:
#Encode months
month_map = {
    "January":1, "February":2, "March":3, "April":4,
    "May":5, "June":6, "July":7, "August":8,
    "September":9, "October":10, "November":11, "December":12
}

df["Month_Num"] = df["Month"].map(month_map)

In [10]:
df.head()

,Year,Month,Nationality,Arrivals,Avg_Stay,Revenue_USD,Month_Num
0,2025,January,India,45496,6.8,58310242.0,1
1,2025,January,Russian Federation,37914,12.5,89335013.0,1
2,2025,January,United Kingdom,20220,13.2,50311716.0,1
3,2025,January,Germany,17693,14.2,47358358.0,1
4,2025,January,China,15165,8.5,24300108.0,1

In [11]:
df = df.sort_values(["Nationality", "Year", "Month_Num"])

In [12]:
df["Date"] = pd.to_datetime(
    df["Year"].astype(str) + "-" + df["Month_Num"].astype(str) + "-01"
)

In [13]:
df["Month_Name"] = df["Date"].dt.month_name()

seasonality = (
    df.groupby(["Nationality", "Month_Name"])["Arrivals"]
      .mean()
      .reset_index()
)

In [14]:
peak_months = (
    seasonality
    .sort_values(["Nationality", "Arrivals"], ascending=False)
    .groupby("Nationality")
    .first()
)

peak_months

                   Month_Name      Arrivals
Nationality
Australia            December   9064.272727
Bangladesh                May   7975.000000
Belarus              February     44.000000
Canada                   July   3852.166667
China                February  18255.000000
France               February  10789.700000
Germany              February  12495.545455
India                December  36736.181818
Iran                    March   3738.000000
Israel              September   4162.000000
Italy                  August   7940.000000
Japan                  August   4638.333333
Kazakhastan             March   1514.000000
Kazakhstan              March   4946.000000
Maldives             December   6264.777778
Netherlands              July   6227.444444
Norway                   June     32.000000
Others               December  63884.000000
Pakistan                 June   5529.000000
Poland               February   6217.250000
Russia               December  12266.000000
Russian Federation   February  20892.142857
Saudi Arabia             June   1500.000000
Spain                    July   5912.000000
Switzerland             April   2057.000000
UK                   December  24845.250000
USA                  December   7677.400000
Ukraine               January   6066.000000
United Kingdom        January  16662.166667
United States        December   6604.400000
United states           March    182.000000
canada               December   6512.000000
china                February  28039.000000
france               December   3021.000000
india                 January  41448.000000
others                January  81216.000000
spain                 October    269.000000
ukraine              November   4770.000000
united states           March  12543.000000