<a href="https://colab.research.google.com/github/kaveesha82/DS_Project/blob/component-1/arrival_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_excel('/content/drive/MyDrive/DSGP/monthlyarrivals.xlsx')

In [4]:
#Clean column names
df.columns = df.columns.str.strip()

#Remove commas inside numbers
df = df.replace(",", "", regex=True)


df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1056 entries, 0 to 1055
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Year         1056 non-null   int64
 1   Month        1056 non-null   object
 2   Nationality  1056 non-null   object
 3   Arrivals     1056 non-null   int64
 4   Avg_Stay     1056 non-null   float64
 5   Revenue_USD  1056 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 49.6+ KB

In [6]:
df.shape

(1056, 6)

In [7]:
df.columns

Index(['Year', 'Month', 'Nationality', 'Arrivals', 'Avg_Stay', 'Revenue_USD'], dtype='object')

In [8]:
df.dtypes

Year             int64
Month           object
Nationality     object
Arrivals         int64
Avg_Stay       float64
Revenue_USD    float64
dtype: object

In [9]:
df.isnull().sum()

Year           0
Month          0
Nationality    0
Arrivals       0
Avg_Stay       0
Revenue_USD    0
dtype: int64